apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-configs
data:
  SMTP_SERVER: '{{.Values.postfixImage.smtpServer}}'
  SMTP_PORT: '{{.Values.postfixImage.smtpPort}}'
  SMTP_USERNAME: '{{.Values.postfixImage.username}}'
  SMTP_PASSWORD: '{{.Values.postfixImage.password}}'
  SERVER_HOSTNAME: '{{.Values.postfixImage.serverHostname}}'
  OVERWRITE_FROM: '{{.Values.postfixImage.overwriteFrom}}'
  SENDER_CANONICAL: '{{.Values.postfixImage.senderCanonical}}'
