---
apiVersion: v1
kind: Service
metadata:
  name: postfix-service
spec:
  type: ClusterIP
  ports:
    - port: 25
      protocol: TCP
      targetPort: 25
  selector:
    app: postfix
    tier: backend
