apiVersion: v1
kind: ConfigMap
metadata:
  name: indexity-api-configs
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_DB: indexity
  POSTGRES_USERNAME: user
  POSTGRES_PASSWORD: password
  REDIS_HOST: redis-master-service
  UI_HOSTNAME: '{{.Values.domainName}}'
  UI_PROTOCOL: '{{.Values.protocol}}'
  UI_PORT: '{{.Values.port}}'
  REDIS_ENABLED: 'true'
  NODE_ENV: '{{.Values.env}}'
  STRUCTURE_TRACKER_API_HOST: 'http://indexity-tracker-service'
  STRUCTURE_TRACKER_API_PORT: '8084'
  ENABLE_SWAGGER_UI: '{{.Values.indexityApiImage.enableSwagger}}'
  ADMIN_EMAIL: '{{.Values.indexityApiImage.adminEmail}}'
  SMTP_HOST: '{{.Values.indexityApiImage.smtpHost}}'
  SMTP_PORT: '{{.Values.indexityApiImage.smtpPort}}'
  SMTP_USE_SSL: '{{.Values.indexityApiImage.smtpUseSsl}}'
  MAIL_FROM: '{{.Values.indexityApiImage.mailFrom}}'
  TRACKER_NAME: '{{.Values.trackerName}}'
  TRACKER_EMAIL: '{{.Values.trackerEmail}}'
  TRACKER_PASSWORD: '{{.Values.trackerPassword}}'
