---
apiVersion: v1
kind: Service
metadata:
  name: indexity-api-service
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: indexity-api
    tier: backend
