export enum VIDEO_ANNOTATION_STATE {
  ANNOTATION_NOT_REQUIRED = 'ANNOTATION_NOT_REQUIRED',
  ANNOTATION_PENDING = 'ANNOTATION_PENDING',
  ANNOTATING = 'ANNOTATING',
  ANNOTATION_FINISHED = 'ANNOTATION_FINISHED',
}

export const publicTransitionsFrom = {
  [VIDEO_ANNOTATION_STATE.ANNOTATION_NOT_REQUIRED]: [],
  [VIDEO_ANNOTATION_STATE.ANNOTATION_PENDING]: [
    VIDEO_ANNOTATION_STATE.ANNOTATING,
  ],
  [VIDEO_ANNOTATION_STATE.ANNOTATING]: [
    VIDEO_ANNOTATION_STATE.ANNOTATION_FINISHED,
  ],
  [VIDEO_ANNOTATION_STATE.ANNOTATION_FINISHED]: [
    VIDEO_ANNOTATION_STATE.ANNOTATING,
  ],
};
