---
apiVersion: v1
kind: Service
metadata:
  name: indexity-admin-service
spec:
  type: NodePort
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 80
  selector:
    app: indexity-admin
