apiVersion: v1
kind: Service        # Type of Kubernetes resource
metadata:

  name: redis-master-service # Name of the Kubernetes resource
  labels: # Labels that will be applied to this resource
    app: redis
    tier: backend
spec:
  ports:
    - port: 6379       # Map incoming connections on port 6379 to the target port 6379 of the Pod
      targetPort: 6379
  selector: # Map any Pod with the specified labels to this service
    app: redis
    tier: backend
