apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexity-tracker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: indexity-tracker
  template:
    metadata:
      name: indexity-tracker
      labels:
        app: indexity-tracker
        tier: backend
        env: {{.Values.env}}
        helm-revision: "{{ .Release.Revision }}"
    spec:
      containers:
        - name: indexity-tracker
          image: "{{.Values.indexityTrackerImage.registry}}/{{.Values.indexityTrackerImage.repo}}:{{.Values.indexityTrackerImage.tag}}"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: api-port
              path: /
            initialDelaySeconds: 40
            timeoutSeconds: 10
          ports:
            - name: api-port
              containerPort: 8084
          envFrom:
            - configMapRef:
                name: indexity-tracker-configs
          volumeMounts:
            - mountPath: /indexity-tracker/videos
              subPath: videos
              name: indexity-tracker-volume
      imagePullSecrets:
        - name: docker-reg-key
      volumes:
        - name: indexity-tracker-volume
          persistentVolumeClaim:
            claimName: api-storage-claim
      restartPolicy: Always
